In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Indonesia' 33.0 72000.0]
 ['Palestina' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Palestina' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['Indonesia' 35.0 58000.0]
 ['Palestina' nan 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Germany' 40.0 35000.0]
 ['Indonesia' 37.0 50000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Indonesia' 33.0 72000.0]
 ['Palestina' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Palestina' 38.0 61000.0]
 ['Germany' 40.0 56555.555555555555]
 ['Indonesia' 35.0 58000.0]
 ['Palestina' 36.44444444444444 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Germany' 40.0 35000.0]
 ['Indonesia' 37.0 50000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 1.0 0.0 33.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 56555.555555555555]
 [0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 36.44444444444444 52000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 40.0 35000.0]
 [0.0 1.0 0.0 37.0 50000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 0.0 1.0 36.44444444444444 52000.0]
 [1.0 0.0 0.0 40.0 56555.555555555555]
 [0.0 1.0 0.0 33.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 40.0 35000.0]
 [0.0 1.0 0.0 35.0 58000.0]]


In [14]:
print(x_test)

[[1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 37.0 50000.0]]


In [15]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 -0.1291105531182616 -0.44460388403608264]
 [1.0 0.0 0.0 0.49451777892466003 -0.08892077680721665]
 [0.0 1.0 0.0 -0.7332504997848414 1.1169317086760122]
 [0.0 0.0 1.0 0.14372684215051676 0.25808713268436007]
 [0.0 0.0 1.0 -1.7856233101072712 -0.7569110025785016]
 [0.0 1.0 0.0 1.897681526021233 1.6634691661252456]
 [1.0 0.0 0.0 0.49451777892466003 -1.7719091378413634]
 [0.0 1.0 0.0 -0.3824595630106981 0.02385679377754583]]


In [19]:
print(x_test)

[[1.0 0.0 0.0 -1.2594369049460563 -0.28845032476487314]
 [0.0 1.0 0.0 -0.03166862623655488 -0.6007574433072922]]
